### PR TITLE
WIP: Build with the same configure flags as corresponding MSYS2 packages

### PR DESCRIPTION
**Pull request by Blackhex**
Specify with what configure options the MSYS2 packages are being build also for other packages.

This PR serves as a reference for now and should not be merged.

### CODE REVIEW

**Comment by ZacWalk** [comment]
This also seems obsolete. Are all wanted changes already in main?

**Comment by Blackhex** [comment]
> This also seems obsolete. Are all wanted changes already in main?

Let me double-check... Some of the configure options were not applied to pass the build but they should at leats be mentioned in the comments.

**Comment by Blackhex** [comment]
Updated

**Comment by Blackhex** [comment]
Closing for now to keep our PR list clean.

**Pull request closed without merging**
